import joblib
from text_preparation import text_preparation

def train_classifier():
    from sklearn.feature_extraction.text import TfidfVectorizer
    from sklearn.model_selection import cross_val_predict
    from sklearn.naive_bayes import MultinomialNB
    from sklearn.pipeline import Pipeline
    import json

    with open("../training_data/extracted_data.json", "r", encoding="utf-8") as f:
        data = json.load(f)

    prepared_texts = [text_preparation(doc) for doc in data["texts"]]

    tfidf_vectorizer = TfidfVectorizer(stop_words='english', max_df=0.95, min_df=2)
    model = MultinomialNB()

    pipline = Pipeline([
        ("vectorizer", tfidf_vectorizer),
        ("model", model)
    ])

    pipline.fit(prepared_texts, data["labels"])

    # Навчання
    y_pred = cross_val_predict(pipline, prepared_texts, data["labels"], cv=3)

    try:
        joblib.dump(pipline, "../models/classifier.joblib")
        print(f"Trained classifier was written to file classifier.joblib")
    except Exception as e:
        print(f"Error while saving classifier {e}")

# # Результати
# print("Accuracy:", accuracy_score(data["labels"], y_pred))
# print("\nClassification Report:\n", classification_report(data["labels"], y_pred))


def classify(text: str):
    try:
        model = joblib.load('../models/classifier.joblib')
        print("Classifier loaded successfully")
    except Exception as e:
        print(f"Unable to load classifier {e}")
        return "Unable to load classifier"

    prepared_text = text_preparation(text)
    prediction = model.predict([prepared_text])
    return prediction


if __name__ == '__main__':
    train_classifier()
    # prepared_text = text_preparation("""Title: Investigation of Magnetic Field Variations Near Household Electronic Devices
    #
    # Abstract:
    # This research investigates the spatial variation of magnetic field strength near common household electronic devices such as laptops, chargers, refrigerators, and electric kettles. Using a Gaussmeter, magnetic field measurements were recorded at varying distances (5 cm to 1 m) from the devices during operation. The results demonstrate a clear exponential decay in field strength with distance and highlight localized anomalies near power supply units. Findings contribute to understanding potential exposure risks and support guidelines for safe device usage.
    #
    # Introduction:
    # Magnetic fields generated by electronic appliances are a source of low-frequency electromagnetic radiation in residential environments. While generally weak, chronic exposure to stronger localized fields may have biological effects. This study aims to measure and analyze magnetic field distribution around typical household electronics to map exposure levels and detect anomalies.
    #
    # Methodology:
    # Devices were placed in a controlled room, and a Gaussmeter was used to measure the magnetic field intensity at multiple distances. Each device was tested in both idle and active states. Readings were taken in three spatial dimensions to capture the field variation.
    #
    # Results:
    #
    # The highest fields were recorded near the charging adapters and the back of refrigerators.
    #
    # All devices showed a sharp drop in field intensity beyond 30 cm.
    #
    # Some readings exceeded 2 µT within 10 cm, above typical background levels (~0.05 µT).
    #
    # Conclusion:
    # The study confirms that while most household electronics produce relatively low magnetic fields, significant variations occur near power components. This data is useful for informing placement strategies and exposure minimization, especially in environments with prolonged human-device proximity.""")
    text ="""Quick Start Guide – SmartAir 2000 Air Purifier
    Unboxing: Remove the device from packaging. Ensure the HEPA filter is installed correctly before first use.
    
    Placement: Position the unit on a flat surface, at least 20 cm away from walls.
    
    Power On: Plug into a standard AC outlet. Press the Power button on the control panel.
    
    Modes: Use the Mode button to switch between Auto, Sleep, and Turbo.
    
    Filter Reset: After 2000 hours of use, the Filter Indicator will blink. Replace the filter and hold the Reset button for 3 seconds.
    
    Maintenance: Clean the exterior weekly using a soft, dry cloth."""

    print(classify(text))